"""updating medic document from unique to not unique

Revision ID: 2b846579fb03
Revises: d7663c40ef34
Create Date: 2024-05-10 02:01:41.262671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b846579fb03'
down_revision: Union[str, None] = 'd7663c40ef34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_medical_document', table_name='users')
    op.create_index(op.f('ix_users_medical_document'), 'users', ['medical_document'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_medical_document'), table_name='users')
    op.create_index('ix_users_medical_document', 'users', ['medical_document'], unique=True)
    # ### end Alembic commands ###
