"""reviewing

Revision ID: 3029184e8c5e
Revises: 
Create Date: 2024-05-23 23:21:35.446534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3029184e8c5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_ibfk_1', 'chats', type_='foreignkey')
    op.drop_column('chats', 'chat_history_id')
    op.add_column('chats_history', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chats_history', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats_history', type_='foreignkey')
    op.drop_column('chats_history', 'chat_id')
    op.add_column('chats', sa.Column('chat_history_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('chats_ibfk_1', 'chats', 'chats_history', ['chat_history_id'], ['id'])
    # ### end Alembic commands ###
