"""adjusting chats with user id

Revision ID: 415869681065
Revises: 29dfc0d4d48b
Create Date: 2024-05-24 02:41:25.595606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415869681065'
down_revision: Union[str, None] = '29dfc0d4d48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bot_sender', 'chats_history', type_='foreignkey')
    op.drop_constraint('fk_user_sender', 'chats_history', type_='foreignkey')
    op.create_foreign_key(None, 'chats_history', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats_history', type_='foreignkey')
    op.create_foreign_key('fk_user_sender', 'chats_history', 'users', ['sender_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('fk_bot_sender', 'chats_history', 'bots', ['sender_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
